#!/usr/bin/env python
# -*- coding: utf-8 -*-
# Simple quotes database with Python and SQLite3.
#
# Usage
# This script will read the environment variable 'IRC_NICKNAME' to set the
# 'author' column of new added quotes.
#
# To add a new quote:
# ./quotes ./my-db.sqlite add "non è davvero funzionante"
#
# To get a random quote:
# ./quotes ./my-db.sqlite read
#
# To get the ID quote:
# ./quotes ./my-db.sqlite read <ID>
#
# Daniel Kertesz <daniel@spatof.org>
import os
import sys
from datetime import datetime
from optparse import OptionParser
import sqlite3


def init_db(filename):
    """Initialize database connection and create SCHEMA if needed"""

    create = not os.path.exists(filename)
    conn = sqlite3.connect(filename)

    if create:
        c = conn.cursor()
        c.execute('''CREATE TABLE if not exists quotes
        (id INTEGER NOT NULL, creation_date DATETIME, author VARCHAR, quote TEXT,
        karma INTEGER, PRIMARY KEY (id))''')
        conn.commit()

    return conn

def random_quote(conn, args=''):
    """Return a random quote from the database"""
    c = conn.cursor()

    if args:
        c.execute('SELECT id, quote FROM quotes WHERE id=?', (args,))
    else:
        c.execute('SELECT id, quote FROM quotes ORDER BY RANDOM() LIMIT 1;')
    row = c.fetchone()
    if not row:
        print "Quote not found"
        return 1

    quote = row[1].encode('utf-8')
    print "%d: %s" % (row[0], quote)


def add_quote(conn, author, quote):
    """Add a new quote to the database"""

    c = conn.cursor()

    now = datetime.now()
    if not isinstance(quote, unicode):
        quote = unicode(quote, 'utf-8')

    values = (now, author, quote, 0)
    c.execute('''INSERT INTO quotes(creation_date, author, quote, karma)
    VALUES (?, ?, ?, ?)''', values)
    conn.commit()
    _id = c.lastrowid
    print "Added quote %d" % int(_id)


def main():
    parser = OptionParser()
    parser.add_option('-d', '--db', help="SQLite database file; env: QUOTES_DB")
    (opts, args) = parser.parse_args()
    db_file = opts.db or os.environ.get('QUOTES_DB')
    if not db_file:
        parser.error("You must specify a database file")
    elif not args:
        parser.error("You must specify a command: 'read' or 'add'")

    command = args.pop(0)
    if args:
        args = ' '.join(args[1:])

    conn = init_db(db_file)
    rv = 0
    if command == 'read':
        rv = random_quote(conn, args)
    elif command == 'add':
        if args:
            author = os.environ.get('IRC_NICKNAME', 'unknown')
            rv = add_quote(conn, author, args)
        else:
            parser.error("You must specify a quote to add")

    conn.close()
    sys.exit(rv)

if __name__ == '__main__':
    main()
